version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: arbitrage:${ARBITRAGE_VERSION:-latest}
    restart: always
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      ARBITRAGE_HOST: 0.0.0.0
      ARBITRAGE_DB_HOST: arbitrage-db
      ARBITRAGE_DB_PORT: 5432
      ARBITRAGE_DB_USER: arbitrage
      ARBITRAGE_DB_PASS: arbitrage
      ARBITRAGE_DB_BASE: arbitrage
      TESTKAFKA_KAFKA_BOOTSTRAP_SERVERS: '["arbitrage-kafka:9092"]'

  db:
    image: postgres:13.8-bullseye
    hostname: arbitrage-db
    environment:
      POSTGRES_PASSWORD: "arbitrage"
      POSTGRES_USER: "arbitrage"
      POSTGRES_DB: "arbitrage"
    volumes:
    - arbitrage-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U arbitrage
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: arbitrage:${ARBITRAGE_VERSION:-latest}
    restart: "no"
    command: aerich upgrade
    environment:
      ARBITRAGE_DB_HOST: arbitrage-db
      ARBITRAGE_DB_PORT: 5432
      ARBITRAGE_DB_USER: arbitrage
      ARBITRAGE_DB_PASS: arbitrage
      ARBITRAGE_DB_BASE: arbitrage
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: bitnami/redis:6.2.5
    hostname: "arbitrage-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  zookeeper:
    image: "bitnami/zookeeper:3.7.1"
    hostname: "arbitrage-zookeeper"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_LOG_LEVEL: "ERROR"
    healthcheck:
      test: zkServer.sh status
      interval: 1s
      timeout: 3s
      retries: 30

  kafka:
    image: "bitnami/kafka:3.2.0"
    hostname: "arbitrage-kafka"
    environment:
      KAFKA_BROKER_ID: "1"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://arbitrage-kafka:9092"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "arbitrage-zookeeper:2181"
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 1s
      timeout: 3s
      retries: 30
    depends_on:
      zookeeper:
        condition: service_healthy



volumes:
  arbitrage-db-data:
    name: arbitrage-db-data
